name:          Objectiv Component Library
title:         Objectiv Component Library
description:   Site components for working with Objectiv's starter theme
url:           https://objectivco.github.io/
baseurl:       /
permalink: none
author:
  name:    Wes Cole
  email:   wes@objectiv.co
  github:  objectivco
  twitter: objectivco
encoding:      utf-8
markdown:      kramdown
highlighter:   rouge
kramdown:
  input: GFM
sass:
  sass_dir: assets/css/sass
collections:
  component:
    output: true
